/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Asset_StatusEnum {

    // Installed
    INSTALLED("Installed"),

    // Obsolete
    OBSOLETE("Obsolete"),

    // Purchased
    PURCHASED("Purchased"),

    // Registered
    REGISTERED("Registered"),

    // Shipped
    SHIPPED("Shipped");


    final String value;

    private Asset_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Asset_StatusEnum fromValue(String value) {
        for (Asset_StatusEnum e : Asset_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
