/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Campaign_StatusEnum {

    // Aborted
    ABORTED("Aborted"),

    // Completed
    COMPLETED("Completed"),

    // In Progress
    IN_PROGRESS("In Progress"),

    // Planned
    PLANNED("Planned");


    final String value;

    private Campaign_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Campaign_StatusEnum fromValue(String value) {
        for (Campaign_StatusEnum e : Campaign_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
