/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Campaign_TypeEnum {

    // Advertisement
    ADVERTISEMENT("Advertisement"),

    // Banner Ads
    BANNER_ADS("Banner Ads"),

    // Conference
    CONFERENCE("Conference"),

    // Direct Mail
    DIRECT_MAIL("Direct Mail"),

    // Email
    EMAIL("Email"),

    // Other
    OTHER("Other"),

    // Partners
    PARTNERS("Partners"),

    // Public Relations
    PUBLIC_RELATIONS("Public Relations"),

    // Referral Program
    REFERRAL_PROGRAM("Referral Program"),

    // Telemarketing
    TELEMARKETING("Telemarketing"),

    // Trade Show
    TRADE_SHOW("Trade Show"),

    // Webinar
    WEBINAR("Webinar");


    final String value;

    private Campaign_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Campaign_TypeEnum fromValue(String value) {
        for (Campaign_TypeEnum e : Campaign_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
