/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ContentLocation
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum ContentVersion_ContentLocationEnum {

    // E
    E("E"),

    // L
    L("L"),

    // S
    S("S");


    final String value;

    private ContentVersion_ContentLocationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ContentVersion_ContentLocationEnum fromValue(String value) {
        for (ContentVersion_ContentLocationEnum e : ContentVersion_ContentLocationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
