/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist SalesVolumeReliability
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum DandBCompany_SalesVolumeReliabilityEnum {

    // 0
    _0("0"),

    // 1
    _1("1"),

    // 2
    _2("2"),

    // 3
    _3("3");


    final String value;

    private DandBCompany_SalesVolumeReliabilityEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_SalesVolumeReliabilityEnum fromValue(String value) {
        for (DandBCompany_SalesVolumeReliabilityEnum e : DandBCompany_SalesVolumeReliabilityEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
