/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist GeoCodeAccuracy
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum DandBCompany_GeoCodeAccuracyEnum {

    // 0
    _0("0"),

    // A
    A("A"),

    // B
    B("B"),

    // C
    C("C"),

    // D
    D("D"),

    // G
    G("G"),

    // H
    H("H"),

    // I
    I("I"),

    // K
    K("K"),

    // L
    L("L"),

    // M
    M("M"),

    // N
    N("N"),

    // P
    P("P"),

    // S
    S("S"),

    // T
    T("T"),

    // Z
    Z("Z");


    final String value;

    private DandBCompany_GeoCodeAccuracyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_GeoCodeAccuracyEnum fromValue(String value) {
        for (DandBCompany_GeoCodeAccuracyEnum e : DandBCompany_GeoCodeAccuracyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
