/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Subsidiary
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum DandBCompany_SubsidiaryEnum {

    // 0
    _0("0"),

    // 3
    _3("3");


    final String value;

    private DandBCompany_SubsidiaryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_SubsidiaryEnum fromValue(String value) {
        for (DandBCompany_SubsidiaryEnum e : DandBCompany_SubsidiaryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
