/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin.
 */
package org.apache.camel.salesforce.dto;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractDescribedSObjectBase;
import org.apache.camel.component.salesforce.api.dto.Attributes;
import org.apache.camel.component.salesforce.api.dto.ChildRelationShip;
import org.apache.camel.component.salesforce.api.dto.InfoUrls;
import org.apache.camel.component.salesforce.api.dto.NamedLayoutInfo;
import org.apache.camel.component.salesforce.api.dto.RecordTypeInfo;
import org.apache.camel.component.salesforce.api.dto.SObjectDescription;
import org.apache.camel.component.salesforce.api.dto.SObjectDescriptionUrls;
import org.apache.camel.component.salesforce.api.dto.SObjectField;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject DandBCompany
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
@XStreamAlias("DandBCompany")
public class DandBCompany extends AbstractDescribedSObjectBase {

    public DandBCompany() {
        getAttributes().setType("DandBCompany");
    }

    private static final SObjectDescription DESCRIPTION = createSObjectDescription();

    private String DunsNumber;

    @JsonProperty("DunsNumber")
    public String getDunsNumber() {
        return this.DunsNumber;
    }

    @JsonProperty("DunsNumber")
    public void setDunsNumber(String DunsNumber) {
        this.DunsNumber = DunsNumber;
    }

    private String Street;

    @JsonProperty("Street")
    public String getStreet() {
        return this.Street;
    }

    @JsonProperty("Street")
    public void setStreet(String Street) {
        this.Street = Street;
    }

    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    private org.apache.camel.component.salesforce.api.dto.Address Address;

    @JsonProperty("Address")
    public org.apache.camel.component.salesforce.api.dto.Address getAddress() {
        return this.Address;
    }

    @JsonProperty("Address")
    public void setAddress(org.apache.camel.component.salesforce.api.dto.Address Address) {
        this.Address = Address;
    }

    private String Phone;

    @JsonProperty("Phone")
    public String getPhone() {
        return this.Phone;
    }

    @JsonProperty("Phone")
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    private String Fax;

    @JsonProperty("Fax")
    public String getFax() {
        return this.Fax;
    }

    @JsonProperty("Fax")
    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    private String CountryAccessCode;

    @JsonProperty("CountryAccessCode")
    public String getCountryAccessCode() {
        return this.CountryAccessCode;
    }

    @JsonProperty("CountryAccessCode")
    public void setCountryAccessCode(String CountryAccessCode) {
        this.CountryAccessCode = CountryAccessCode;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_PublicIndicatorEnum PublicIndicator;

    @JsonProperty("PublicIndicator")
    public DandBCompany_PublicIndicatorEnum getPublicIndicator() {
        return this.PublicIndicator;
    }

    @JsonProperty("PublicIndicator")
    public void setPublicIndicator(DandBCompany_PublicIndicatorEnum PublicIndicator) {
        this.PublicIndicator = PublicIndicator;
    }

    private String StockSymbol;

    @JsonProperty("StockSymbol")
    public String getStockSymbol() {
        return this.StockSymbol;
    }

    @JsonProperty("StockSymbol")
    public void setStockSymbol(String StockSymbol) {
        this.StockSymbol = StockSymbol;
    }

    private String StockExchange;

    @JsonProperty("StockExchange")
    public String getStockExchange() {
        return this.StockExchange;
    }

    @JsonProperty("StockExchange")
    public void setStockExchange(String StockExchange) {
        this.StockExchange = StockExchange;
    }

    private Double SalesVolume;

    @JsonProperty("SalesVolume")
    public Double getSalesVolume() {
        return this.SalesVolume;
    }

    @JsonProperty("SalesVolume")
    public void setSalesVolume(Double SalesVolume) {
        this.SalesVolume = SalesVolume;
    }

    private String URL;

    @JsonProperty("URL")
    public String getURL() {
        return this.URL;
    }

    @JsonProperty("URL")
    public void setURL(String URL) {
        this.URL = URL;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_OutOfBusinessEnum OutOfBusiness;

    @JsonProperty("OutOfBusiness")
    public DandBCompany_OutOfBusinessEnum getOutOfBusiness() {
        return this.OutOfBusiness;
    }

    @JsonProperty("OutOfBusiness")
    public void setOutOfBusiness(DandBCompany_OutOfBusinessEnum OutOfBusiness) {
        this.OutOfBusiness = OutOfBusiness;
    }

    private Double EmployeesTotal;

    @JsonProperty("EmployeesTotal")
    public Double getEmployeesTotal() {
        return this.EmployeesTotal;
    }

    @JsonProperty("EmployeesTotal")
    public void setEmployeesTotal(Double EmployeesTotal) {
        this.EmployeesTotal = EmployeesTotal;
    }

    private String FipsMsaCode;

    @JsonProperty("FipsMsaCode")
    public String getFipsMsaCode() {
        return this.FipsMsaCode;
    }

    @JsonProperty("FipsMsaCode")
    public void setFipsMsaCode(String FipsMsaCode) {
        this.FipsMsaCode = FipsMsaCode;
    }

    private String FipsMsaDesc;

    @JsonProperty("FipsMsaDesc")
    public String getFipsMsaDesc() {
        return this.FipsMsaDesc;
    }

    @JsonProperty("FipsMsaDesc")
    public void setFipsMsaDesc(String FipsMsaDesc) {
        this.FipsMsaDesc = FipsMsaDesc;
    }

    private String TradeStyle1;

    @JsonProperty("TradeStyle1")
    public String getTradeStyle1() {
        return this.TradeStyle1;
    }

    @JsonProperty("TradeStyle1")
    public void setTradeStyle1(String TradeStyle1) {
        this.TradeStyle1 = TradeStyle1;
    }

    private String YearStarted;

    @JsonProperty("YearStarted")
    public String getYearStarted() {
        return this.YearStarted;
    }

    @JsonProperty("YearStarted")
    public void setYearStarted(String YearStarted) {
        this.YearStarted = YearStarted;
    }

    private String MailingStreet;

    @JsonProperty("MailingStreet")
    public String getMailingStreet() {
        return this.MailingStreet;
    }

    @JsonProperty("MailingStreet")
    public void setMailingStreet(String MailingStreet) {
        this.MailingStreet = MailingStreet;
    }

    private String MailingCity;

    @JsonProperty("MailingCity")
    public String getMailingCity() {
        return this.MailingCity;
    }

    @JsonProperty("MailingCity")
    public void setMailingCity(String MailingCity) {
        this.MailingCity = MailingCity;
    }

    private String MailingState;

    @JsonProperty("MailingState")
    public String getMailingState() {
        return this.MailingState;
    }

    @JsonProperty("MailingState")
    public void setMailingState(String MailingState) {
        this.MailingState = MailingState;
    }

    private String MailingPostalCode;

    @JsonProperty("MailingPostalCode")
    public String getMailingPostalCode() {
        return this.MailingPostalCode;
    }

    @JsonProperty("MailingPostalCode")
    public void setMailingPostalCode(String MailingPostalCode) {
        this.MailingPostalCode = MailingPostalCode;
    }

    private String MailingCountry;

    @JsonProperty("MailingCountry")
    public String getMailingCountry() {
        return this.MailingCountry;
    }

    @JsonProperty("MailingCountry")
    public void setMailingCountry(String MailingCountry) {
        this.MailingCountry = MailingCountry;
    }

    private org.apache.camel.component.salesforce.api.dto.Address MailingAddress;

    @JsonProperty("MailingAddress")
    public org.apache.camel.component.salesforce.api.dto.Address getMailingAddress() {
        return this.MailingAddress;
    }

    @JsonProperty("MailingAddress")
    public void setMailingAddress(org.apache.camel.component.salesforce.api.dto.Address MailingAddress) {
        this.MailingAddress = MailingAddress;
    }

    private String Latitude;

    @JsonProperty("Latitude")
    public String getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    private String Longitude;

    @JsonProperty("Longitude")
    public String getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    private String PrimarySic;

    @JsonProperty("PrimarySic")
    public String getPrimarySic() {
        return this.PrimarySic;
    }

    @JsonProperty("PrimarySic")
    public void setPrimarySic(String PrimarySic) {
        this.PrimarySic = PrimarySic;
    }

    private String PrimarySicDesc;

    @JsonProperty("PrimarySicDesc")
    public String getPrimarySicDesc() {
        return this.PrimarySicDesc;
    }

    @JsonProperty("PrimarySicDesc")
    public void setPrimarySicDesc(String PrimarySicDesc) {
        this.PrimarySicDesc = PrimarySicDesc;
    }

    private String SecondSic;

    @JsonProperty("SecondSic")
    public String getSecondSic() {
        return this.SecondSic;
    }

    @JsonProperty("SecondSic")
    public void setSecondSic(String SecondSic) {
        this.SecondSic = SecondSic;
    }

    private String SecondSicDesc;

    @JsonProperty("SecondSicDesc")
    public String getSecondSicDesc() {
        return this.SecondSicDesc;
    }

    @JsonProperty("SecondSicDesc")
    public void setSecondSicDesc(String SecondSicDesc) {
        this.SecondSicDesc = SecondSicDesc;
    }

    private String ThirdSic;

    @JsonProperty("ThirdSic")
    public String getThirdSic() {
        return this.ThirdSic;
    }

    @JsonProperty("ThirdSic")
    public void setThirdSic(String ThirdSic) {
        this.ThirdSic = ThirdSic;
    }

    private String ThirdSicDesc;

    @JsonProperty("ThirdSicDesc")
    public String getThirdSicDesc() {
        return this.ThirdSicDesc;
    }

    @JsonProperty("ThirdSicDesc")
    public void setThirdSicDesc(String ThirdSicDesc) {
        this.ThirdSicDesc = ThirdSicDesc;
    }

    private String FourthSic;

    @JsonProperty("FourthSic")
    public String getFourthSic() {
        return this.FourthSic;
    }

    @JsonProperty("FourthSic")
    public void setFourthSic(String FourthSic) {
        this.FourthSic = FourthSic;
    }

    private String FourthSicDesc;

    @JsonProperty("FourthSicDesc")
    public String getFourthSicDesc() {
        return this.FourthSicDesc;
    }

    @JsonProperty("FourthSicDesc")
    public void setFourthSicDesc(String FourthSicDesc) {
        this.FourthSicDesc = FourthSicDesc;
    }

    private String FifthSic;

    @JsonProperty("FifthSic")
    public String getFifthSic() {
        return this.FifthSic;
    }

    @JsonProperty("FifthSic")
    public void setFifthSic(String FifthSic) {
        this.FifthSic = FifthSic;
    }

    private String FifthSicDesc;

    @JsonProperty("FifthSicDesc")
    public String getFifthSicDesc() {
        return this.FifthSicDesc;
    }

    @JsonProperty("FifthSicDesc")
    public void setFifthSicDesc(String FifthSicDesc) {
        this.FifthSicDesc = FifthSicDesc;
    }

    private String SixthSic;

    @JsonProperty("SixthSic")
    public String getSixthSic() {
        return this.SixthSic;
    }

    @JsonProperty("SixthSic")
    public void setSixthSic(String SixthSic) {
        this.SixthSic = SixthSic;
    }

    private String SixthSicDesc;

    @JsonProperty("SixthSicDesc")
    public String getSixthSicDesc() {
        return this.SixthSicDesc;
    }

    @JsonProperty("SixthSicDesc")
    public void setSixthSicDesc(String SixthSicDesc) {
        this.SixthSicDesc = SixthSicDesc;
    }

    private String PrimaryNaics;

    @JsonProperty("PrimaryNaics")
    public String getPrimaryNaics() {
        return this.PrimaryNaics;
    }

    @JsonProperty("PrimaryNaics")
    public void setPrimaryNaics(String PrimaryNaics) {
        this.PrimaryNaics = PrimaryNaics;
    }

    private String PrimaryNaicsDesc;

    @JsonProperty("PrimaryNaicsDesc")
    public String getPrimaryNaicsDesc() {
        return this.PrimaryNaicsDesc;
    }

    @JsonProperty("PrimaryNaicsDesc")
    public void setPrimaryNaicsDesc(String PrimaryNaicsDesc) {
        this.PrimaryNaicsDesc = PrimaryNaicsDesc;
    }

    private String SecondNaics;

    @JsonProperty("SecondNaics")
    public String getSecondNaics() {
        return this.SecondNaics;
    }

    @JsonProperty("SecondNaics")
    public void setSecondNaics(String SecondNaics) {
        this.SecondNaics = SecondNaics;
    }

    private String SecondNaicsDesc;

    @JsonProperty("SecondNaicsDesc")
    public String getSecondNaicsDesc() {
        return this.SecondNaicsDesc;
    }

    @JsonProperty("SecondNaicsDesc")
    public void setSecondNaicsDesc(String SecondNaicsDesc) {
        this.SecondNaicsDesc = SecondNaicsDesc;
    }

    private String ThirdNaics;

    @JsonProperty("ThirdNaics")
    public String getThirdNaics() {
        return this.ThirdNaics;
    }

    @JsonProperty("ThirdNaics")
    public void setThirdNaics(String ThirdNaics) {
        this.ThirdNaics = ThirdNaics;
    }

    private String ThirdNaicsDesc;

    @JsonProperty("ThirdNaicsDesc")
    public String getThirdNaicsDesc() {
        return this.ThirdNaicsDesc;
    }

    @JsonProperty("ThirdNaicsDesc")
    public void setThirdNaicsDesc(String ThirdNaicsDesc) {
        this.ThirdNaicsDesc = ThirdNaicsDesc;
    }

    private String FourthNaics;

    @JsonProperty("FourthNaics")
    public String getFourthNaics() {
        return this.FourthNaics;
    }

    @JsonProperty("FourthNaics")
    public void setFourthNaics(String FourthNaics) {
        this.FourthNaics = FourthNaics;
    }

    private String FourthNaicsDesc;

    @JsonProperty("FourthNaicsDesc")
    public String getFourthNaicsDesc() {
        return this.FourthNaicsDesc;
    }

    @JsonProperty("FourthNaicsDesc")
    public void setFourthNaicsDesc(String FourthNaicsDesc) {
        this.FourthNaicsDesc = FourthNaicsDesc;
    }

    private String FifthNaics;

    @JsonProperty("FifthNaics")
    public String getFifthNaics() {
        return this.FifthNaics;
    }

    @JsonProperty("FifthNaics")
    public void setFifthNaics(String FifthNaics) {
        this.FifthNaics = FifthNaics;
    }

    private String FifthNaicsDesc;

    @JsonProperty("FifthNaicsDesc")
    public String getFifthNaicsDesc() {
        return this.FifthNaicsDesc;
    }

    @JsonProperty("FifthNaicsDesc")
    public void setFifthNaicsDesc(String FifthNaicsDesc) {
        this.FifthNaicsDesc = FifthNaicsDesc;
    }

    private String SixthNaics;

    @JsonProperty("SixthNaics")
    public String getSixthNaics() {
        return this.SixthNaics;
    }

    @JsonProperty("SixthNaics")
    public void setSixthNaics(String SixthNaics) {
        this.SixthNaics = SixthNaics;
    }

    private String SixthNaicsDesc;

    @JsonProperty("SixthNaicsDesc")
    public String getSixthNaicsDesc() {
        return this.SixthNaicsDesc;
    }

    @JsonProperty("SixthNaicsDesc")
    public void setSixthNaicsDesc(String SixthNaicsDesc) {
        this.SixthNaicsDesc = SixthNaicsDesc;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_OwnOrRentEnum OwnOrRent;

    @JsonProperty("OwnOrRent")
    public DandBCompany_OwnOrRentEnum getOwnOrRent() {
        return this.OwnOrRent;
    }

    @JsonProperty("OwnOrRent")
    public void setOwnOrRent(DandBCompany_OwnOrRentEnum OwnOrRent) {
        this.OwnOrRent = OwnOrRent;
    }

    private Double EmployeesHere;

    @JsonProperty("EmployeesHere")
    public Double getEmployeesHere() {
        return this.EmployeesHere;
    }

    @JsonProperty("EmployeesHere")
    public void setEmployeesHere(Double EmployeesHere) {
        this.EmployeesHere = EmployeesHere;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_EmployeesHereReliabilityEnum EmployeesHereReliability;

    @JsonProperty("EmployeesHereReliability")
    public DandBCompany_EmployeesHereReliabilityEnum getEmployeesHereReliability() {
        return this.EmployeesHereReliability;
    }

    @JsonProperty("EmployeesHereReliability")
    public void setEmployeesHereReliability(DandBCompany_EmployeesHereReliabilityEnum EmployeesHereReliability) {
        this.EmployeesHereReliability = EmployeesHereReliability;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_SalesVolumeReliabilityEnum SalesVolumeReliability;

    @JsonProperty("SalesVolumeReliability")
    public DandBCompany_SalesVolumeReliabilityEnum getSalesVolumeReliability() {
        return this.SalesVolumeReliability;
    }

    @JsonProperty("SalesVolumeReliability")
    public void setSalesVolumeReliability(DandBCompany_SalesVolumeReliabilityEnum SalesVolumeReliability) {
        this.SalesVolumeReliability = SalesVolumeReliability;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_CurrencyCodeEnum CurrencyCode;

    @JsonProperty("CurrencyCode")
    public DandBCompany_CurrencyCodeEnum getCurrencyCode() {
        return this.CurrencyCode;
    }

    @JsonProperty("CurrencyCode")
    public void setCurrencyCode(DandBCompany_CurrencyCodeEnum CurrencyCode) {
        this.CurrencyCode = CurrencyCode;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_LegalStatusEnum LegalStatus;

    @JsonProperty("LegalStatus")
    public DandBCompany_LegalStatusEnum getLegalStatus() {
        return this.LegalStatus;
    }

    @JsonProperty("LegalStatus")
    public void setLegalStatus(DandBCompany_LegalStatusEnum LegalStatus) {
        this.LegalStatus = LegalStatus;
    }

    private Double GlobalUltimateTotalEmployees;

    @JsonProperty("GlobalUltimateTotalEmployees")
    public Double getGlobalUltimateTotalEmployees() {
        return this.GlobalUltimateTotalEmployees;
    }

    @JsonProperty("GlobalUltimateTotalEmployees")
    public void setGlobalUltimateTotalEmployees(Double GlobalUltimateTotalEmployees) {
        this.GlobalUltimateTotalEmployees = GlobalUltimateTotalEmployees;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_EmployeesTotalReliabilityEnum EmployeesTotalReliability;

    @JsonProperty("EmployeesTotalReliability")
    public DandBCompany_EmployeesTotalReliabilityEnum getEmployeesTotalReliability() {
        return this.EmployeesTotalReliability;
    }

    @JsonProperty("EmployeesTotalReliability")
    public void setEmployeesTotalReliability(DandBCompany_EmployeesTotalReliabilityEnum EmployeesTotalReliability) {
        this.EmployeesTotalReliability = EmployeesTotalReliability;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_MinorityOwnedEnum MinorityOwned;

    @JsonProperty("MinorityOwned")
    public DandBCompany_MinorityOwnedEnum getMinorityOwned() {
        return this.MinorityOwned;
    }

    @JsonProperty("MinorityOwned")
    public void setMinorityOwned(DandBCompany_MinorityOwnedEnum MinorityOwned) {
        this.MinorityOwned = MinorityOwned;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_WomenOwnedEnum WomenOwned;

    @JsonProperty("WomenOwned")
    public DandBCompany_WomenOwnedEnum getWomenOwned() {
        return this.WomenOwned;
    }

    @JsonProperty("WomenOwned")
    public void setWomenOwned(DandBCompany_WomenOwnedEnum WomenOwned) {
        this.WomenOwned = WomenOwned;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_SmallBusinessEnum SmallBusiness;

    @JsonProperty("SmallBusiness")
    public DandBCompany_SmallBusinessEnum getSmallBusiness() {
        return this.SmallBusiness;
    }

    @JsonProperty("SmallBusiness")
    public void setSmallBusiness(DandBCompany_SmallBusinessEnum SmallBusiness) {
        this.SmallBusiness = SmallBusiness;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_MarketingSegmentationClusterEnum MarketingSegmentationCluster;

    @JsonProperty("MarketingSegmentationCluster")
    public DandBCompany_MarketingSegmentationClusterEnum getMarketingSegmentationCluster() {
        return this.MarketingSegmentationCluster;
    }

    @JsonProperty("MarketingSegmentationCluster")
    public void setMarketingSegmentationCluster(DandBCompany_MarketingSegmentationClusterEnum MarketingSegmentationCluster) {
        this.MarketingSegmentationCluster = MarketingSegmentationCluster;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_ImportExportAgentEnum ImportExportAgent;

    @JsonProperty("ImportExportAgent")
    public DandBCompany_ImportExportAgentEnum getImportExportAgent() {
        return this.ImportExportAgent;
    }

    @JsonProperty("ImportExportAgent")
    public void setImportExportAgent(DandBCompany_ImportExportAgentEnum ImportExportAgent) {
        this.ImportExportAgent = ImportExportAgent;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_SubsidiaryEnum Subsidiary;

    @JsonProperty("Subsidiary")
    public DandBCompany_SubsidiaryEnum getSubsidiary() {
        return this.Subsidiary;
    }

    @JsonProperty("Subsidiary")
    public void setSubsidiary(DandBCompany_SubsidiaryEnum Subsidiary) {
        this.Subsidiary = Subsidiary;
    }

    private String TradeStyle2;

    @JsonProperty("TradeStyle2")
    public String getTradeStyle2() {
        return this.TradeStyle2;
    }

    @JsonProperty("TradeStyle2")
    public void setTradeStyle2(String TradeStyle2) {
        this.TradeStyle2 = TradeStyle2;
    }

    private String TradeStyle3;

    @JsonProperty("TradeStyle3")
    public String getTradeStyle3() {
        return this.TradeStyle3;
    }

    @JsonProperty("TradeStyle3")
    public void setTradeStyle3(String TradeStyle3) {
        this.TradeStyle3 = TradeStyle3;
    }

    private String TradeStyle4;

    @JsonProperty("TradeStyle4")
    public String getTradeStyle4() {
        return this.TradeStyle4;
    }

    @JsonProperty("TradeStyle4")
    public void setTradeStyle4(String TradeStyle4) {
        this.TradeStyle4 = TradeStyle4;
    }

    private String TradeStyle5;

    @JsonProperty("TradeStyle5")
    public String getTradeStyle5() {
        return this.TradeStyle5;
    }

    @JsonProperty("TradeStyle5")
    public void setTradeStyle5(String TradeStyle5) {
        this.TradeStyle5 = TradeStyle5;
    }

    private String NationalId;

    @JsonProperty("NationalId")
    public String getNationalId() {
        return this.NationalId;
    }

    @JsonProperty("NationalId")
    public void setNationalId(String NationalId) {
        this.NationalId = NationalId;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_NationalIdTypeEnum NationalIdType;

    @JsonProperty("NationalIdType")
    public DandBCompany_NationalIdTypeEnum getNationalIdType() {
        return this.NationalIdType;
    }

    @JsonProperty("NationalIdType")
    public void setNationalIdType(DandBCompany_NationalIdTypeEnum NationalIdType) {
        this.NationalIdType = NationalIdType;
    }

    private String UsTaxId;

    @JsonProperty("UsTaxId")
    public String getUsTaxId() {
        return this.UsTaxId;
    }

    @JsonProperty("UsTaxId")
    public void setUsTaxId(String UsTaxId) {
        this.UsTaxId = UsTaxId;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_GeoCodeAccuracyEnum GeoCodeAccuracy;

    @JsonProperty("GeoCodeAccuracy")
    public DandBCompany_GeoCodeAccuracyEnum getGeoCodeAccuracy() {
        return this.GeoCodeAccuracy;
    }

    @JsonProperty("GeoCodeAccuracy")
    public void setGeoCodeAccuracy(DandBCompany_GeoCodeAccuracyEnum GeoCodeAccuracy) {
        this.GeoCodeAccuracy = GeoCodeAccuracy;
    }

    private Integer FamilyMembers;

    @JsonProperty("FamilyMembers")
    public Integer getFamilyMembers() {
        return this.FamilyMembers;
    }

    @JsonProperty("FamilyMembers")
    public void setFamilyMembers(Integer FamilyMembers) {
        this.FamilyMembers = FamilyMembers;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_MarketingPreScreenEnum MarketingPreScreen;

    @JsonProperty("MarketingPreScreen")
    public DandBCompany_MarketingPreScreenEnum getMarketingPreScreen() {
        return this.MarketingPreScreen;
    }

    @JsonProperty("MarketingPreScreen")
    public void setMarketingPreScreen(DandBCompany_MarketingPreScreenEnum MarketingPreScreen) {
        this.MarketingPreScreen = MarketingPreScreen;
    }

    private String GlobalUltimateDunsNumber;

    @JsonProperty("GlobalUltimateDunsNumber")
    public String getGlobalUltimateDunsNumber() {
        return this.GlobalUltimateDunsNumber;
    }

    @JsonProperty("GlobalUltimateDunsNumber")
    public void setGlobalUltimateDunsNumber(String GlobalUltimateDunsNumber) {
        this.GlobalUltimateDunsNumber = GlobalUltimateDunsNumber;
    }

    private String GlobalUltimateBusinessName;

    @JsonProperty("GlobalUltimateBusinessName")
    public String getGlobalUltimateBusinessName() {
        return this.GlobalUltimateBusinessName;
    }

    @JsonProperty("GlobalUltimateBusinessName")
    public void setGlobalUltimateBusinessName(String GlobalUltimateBusinessName) {
        this.GlobalUltimateBusinessName = GlobalUltimateBusinessName;
    }

    private String ParentOrHqDunsNumber;

    @JsonProperty("ParentOrHqDunsNumber")
    public String getParentOrHqDunsNumber() {
        return this.ParentOrHqDunsNumber;
    }

    @JsonProperty("ParentOrHqDunsNumber")
    public void setParentOrHqDunsNumber(String ParentOrHqDunsNumber) {
        this.ParentOrHqDunsNumber = ParentOrHqDunsNumber;
    }

    private String ParentOrHqBusinessName;

    @JsonProperty("ParentOrHqBusinessName")
    public String getParentOrHqBusinessName() {
        return this.ParentOrHqBusinessName;
    }

    @JsonProperty("ParentOrHqBusinessName")
    public void setParentOrHqBusinessName(String ParentOrHqBusinessName) {
        this.ParentOrHqBusinessName = ParentOrHqBusinessName;
    }

    private String DomesticUltimateDunsNumber;

    @JsonProperty("DomesticUltimateDunsNumber")
    public String getDomesticUltimateDunsNumber() {
        return this.DomesticUltimateDunsNumber;
    }

    @JsonProperty("DomesticUltimateDunsNumber")
    public void setDomesticUltimateDunsNumber(String DomesticUltimateDunsNumber) {
        this.DomesticUltimateDunsNumber = DomesticUltimateDunsNumber;
    }

    private String DomesticUltimateBusinessName;

    @JsonProperty("DomesticUltimateBusinessName")
    public String getDomesticUltimateBusinessName() {
        return this.DomesticUltimateBusinessName;
    }

    @JsonProperty("DomesticUltimateBusinessName")
    public void setDomesticUltimateBusinessName(String DomesticUltimateBusinessName) {
        this.DomesticUltimateBusinessName = DomesticUltimateBusinessName;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_LocationStatusEnum LocationStatus;

    @JsonProperty("LocationStatus")
    public DandBCompany_LocationStatusEnum getLocationStatus() {
        return this.LocationStatus;
    }

    @JsonProperty("LocationStatus")
    public void setLocationStatus(DandBCompany_LocationStatusEnum LocationStatus) {
        this.LocationStatus = LocationStatus;
    }

    @XStreamConverter(PicklistEnumConverter.class)
    private DandBCompany_CompanyCurrencyIsoCodeEnum CompanyCurrencyIsoCode;

    @JsonProperty("CompanyCurrencyIsoCode")
    public DandBCompany_CompanyCurrencyIsoCodeEnum getCompanyCurrencyIsoCode() {
        return this.CompanyCurrencyIsoCode;
    }

    @JsonProperty("CompanyCurrencyIsoCode")
    public void setCompanyCurrencyIsoCode(DandBCompany_CompanyCurrencyIsoCodeEnum CompanyCurrencyIsoCode) {
        this.CompanyCurrencyIsoCode = CompanyCurrencyIsoCode;
    }

    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

     private QueryRecordsAccount Accounts;

    @JsonProperty("Accounts")
    public QueryRecordsAccount getAccounts() {
        return Accounts;
    }

    @JsonProperty("Accounts")
    public void setAccounts(QueryRecordsAccount Accounts) {
        this.Accounts = Accounts;
    }
    private QueryRecordsLead Leads;

    @JsonProperty("Leads")
    public QueryRecordsLead getLeads() {
        return Leads;
    }

    @JsonProperty("Leads")
    public void setLeads(QueryRecordsLead Leads) {
        this.Leads = Leads;
    }

    @Override
    public final SObjectDescription description() {
        return DESCRIPTION;
    }

    private static SObjectDescription createSObjectDescription() {
        final SObjectDescription description = new SObjectDescription();



        final List<SObjectField> fields1 = new ArrayList<>();
        description.setFields(fields1);

        final SObjectField sObjectField1 = createField("Id", "D&B Company ID", "id", "tns:ID", 18, false, false, false, false, false, false, true);
        fields1.add(sObjectField1);
        final SObjectField sObjectField2 = createField("IsDeleted", "Deleted", "boolean", "xsd:boolean", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField2);
        final SObjectField sObjectField3 = createField("Name", "Primary Business Name", "string", "xsd:string", 255, false, false, true, false, false, false, true);
        fields1.add(sObjectField3);
        final SObjectField sObjectField4 = createField("CreatedDate", "Created Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField4);
        final SObjectField sObjectField5 = createField("CreatedById", "Created By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField5);
        final SObjectField sObjectField6 = createField("LastModifiedDate", "Last Modified Date", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField6);
        final SObjectField sObjectField7 = createField("LastModifiedById", "Last Modified By ID", "reference", "tns:ID", 18, false, false, false, false, false, false, false);
        fields1.add(sObjectField7);
        final SObjectField sObjectField8 = createField("SystemModstamp", "System Modstamp", "datetime", "xsd:dateTime", 0, false, false, false, false, false, false, false);
        fields1.add(sObjectField8);
        final SObjectField sObjectField9 = createField("LastViewedDate", "Last Viewed Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField9);
        final SObjectField sObjectField10 = createField("LastReferencedDate", "Last Referenced Date", "datetime", "xsd:dateTime", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField10);
        final SObjectField sObjectField11 = createField("DunsNumber", "D-U-N-S Number", "string", "xsd:string", 9, true, false, false, false, false, true, true);
        fields1.add(sObjectField11);
        final SObjectField sObjectField12 = createField("Street", "Street Address", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField12);
        final SObjectField sObjectField13 = createField("City", "City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField13);
        final SObjectField sObjectField14 = createField("State", "State", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField14);
        final SObjectField sObjectField15 = createField("PostalCode", "Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField15);
        final SObjectField sObjectField16 = createField("Country", "Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField16);
        final SObjectField sObjectField17 = createField("Address", "Primary Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField17);
        final SObjectField sObjectField18 = createField("Phone", "Telephone Number", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField18);
        final SObjectField sObjectField19 = createField("Fax", "Facsimile Number", "phone", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField19);
        final SObjectField sObjectField20 = createField("CountryAccessCode", "International Dialing Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField20);
        final SObjectField sObjectField21 = createField("PublicIndicator", "Ownership Type Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField21);
        final SObjectField sObjectField22 = createField("StockSymbol", "Ticker Symbol", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField22);
        final SObjectField sObjectField23 = createField("StockExchange", "Stock Exchange", "string", "xsd:string", 16, false, true, false, false, false, false, false);
        fields1.add(sObjectField23);
        final SObjectField sObjectField24 = createField("SalesVolume", "Annual Sales Volume", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField24);
        final SObjectField sObjectField25 = createField("URL", "URL", "url", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField25);
        final SObjectField sObjectField26 = createField("OutOfBusiness", "Out Of Business Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField26);
        final SObjectField sObjectField27 = createField("EmployeesTotal", "Number of Employees - Total", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField27);
        final SObjectField sObjectField28 = createField("FipsMsaCode", "FIPS MSA Code", "string", "xsd:string", 5, false, true, false, false, false, false, false);
        fields1.add(sObjectField28);
        final SObjectField sObjectField29 = createField("FipsMsaDesc", "FIPS MSA Code Description", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField29);
        final SObjectField sObjectField30 = createField("TradeStyle1", "Primary Tradestyle", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField30);
        final SObjectField sObjectField31 = createField("YearStarted", "Year Started", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField31);
        final SObjectField sObjectField32 = createField("MailingStreet", "Mailing Street Address", "textarea", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField32);
        final SObjectField sObjectField33 = createField("MailingCity", "Mailing City", "string", "xsd:string", 40, false, true, false, false, false, false, false);
        fields1.add(sObjectField33);
        final SObjectField sObjectField34 = createField("MailingState", "Mailing State", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField34);
        final SObjectField sObjectField35 = createField("MailingPostalCode", "Mailing Postal Code", "string", "xsd:string", 20, false, true, false, false, false, false, false);
        fields1.add(sObjectField35);
        final SObjectField sObjectField36 = createField("MailingCountry", "Mailing Country", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField36);
        final SObjectField sObjectField37 = createField("MailingAddress", "Mailing Address", "address", "urn:address", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField37);
        final SObjectField sObjectField38 = createField("Latitude", "Latitude", "string", "xsd:string", 11, false, true, false, false, false, false, false);
        fields1.add(sObjectField38);
        final SObjectField sObjectField39 = createField("Longitude", "Longitude", "string", "xsd:string", 11, false, true, false, false, false, false, false);
        fields1.add(sObjectField39);
        final SObjectField sObjectField40 = createField("PrimarySic", "Primary SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField40);
        final SObjectField sObjectField41 = createField("PrimarySicDesc", "Primary SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField41);
        final SObjectField sObjectField42 = createField("SecondSic", "Second SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField42);
        final SObjectField sObjectField43 = createField("SecondSicDesc", "Second SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField43);
        final SObjectField sObjectField44 = createField("ThirdSic", "Third SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField44);
        final SObjectField sObjectField45 = createField("ThirdSicDesc", "Third SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField45);
        final SObjectField sObjectField46 = createField("FourthSic", "Fourth SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField46);
        final SObjectField sObjectField47 = createField("FourthSicDesc", "Fourth SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField47);
        final SObjectField sObjectField48 = createField("FifthSic", "Fifth SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField48);
        final SObjectField sObjectField49 = createField("FifthSicDesc", "Fifth SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField49);
        final SObjectField sObjectField50 = createField("SixthSic", "Sixth SIC Code", "string", "xsd:string", 4, false, true, false, false, false, false, false);
        fields1.add(sObjectField50);
        final SObjectField sObjectField51 = createField("SixthSicDesc", "Sixth SIC Description", "string", "xsd:string", 80, false, true, false, false, false, false, false);
        fields1.add(sObjectField51);
        final SObjectField sObjectField52 = createField("PrimaryNaics", "Primary NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField52);
        final SObjectField sObjectField53 = createField("PrimaryNaicsDesc", "Primary NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField53);
        final SObjectField sObjectField54 = createField("SecondNaics", "Second NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField54);
        final SObjectField sObjectField55 = createField("SecondNaicsDesc", "Second NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField55);
        final SObjectField sObjectField56 = createField("ThirdNaics", "Third NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField56);
        final SObjectField sObjectField57 = createField("ThirdNaicsDesc", "Third NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField57);
        final SObjectField sObjectField58 = createField("FourthNaics", "Fourth NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField58);
        final SObjectField sObjectField59 = createField("FourthNaicsDesc", "Fourth NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField59);
        final SObjectField sObjectField60 = createField("FifthNaics", "Fifth NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField60);
        final SObjectField sObjectField61 = createField("FifthNaicsDesc", "Fifth NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField61);
        final SObjectField sObjectField62 = createField("SixthNaics", "Sixth NAICS Code", "string", "xsd:string", 6, false, true, false, false, false, false, false);
        fields1.add(sObjectField62);
        final SObjectField sObjectField63 = createField("SixthNaicsDesc", "Sixth NAICS Description", "string", "xsd:string", 120, false, true, false, false, false, false, false);
        fields1.add(sObjectField63);
        final SObjectField sObjectField64 = createField("OwnOrRent", "Location Ownership Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField64);
        final SObjectField sObjectField65 = createField("EmployeesHere", "Number of Employees - Location", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField65);
        final SObjectField sObjectField66 = createField("EmployeesHereReliability", "Number of Employees - Location Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField66);
        final SObjectField sObjectField67 = createField("SalesVolumeReliability", "Annual Sales Volume Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField67);
        final SObjectField sObjectField68 = createField("CurrencyCode", "Local Currency Code", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField68);
        final SObjectField sObjectField69 = createField("LegalStatus", "Legal Structure", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField69);
        final SObjectField sObjectField70 = createField("GlobalUltimateTotalEmployees", "Number of Employees - Global", "double", "xsd:double", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField70);
        final SObjectField sObjectField71 = createField("EmployeesTotalReliability", "Number of Employees - Total Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField71);
        final SObjectField sObjectField72 = createField("MinorityOwned", "Minority-Owned Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField72);
        final SObjectField sObjectField73 = createField("WomenOwned", "Woman-Owned Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField73);
        final SObjectField sObjectField74 = createField("SmallBusiness", "Small Business Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField74);
        final SObjectField sObjectField75 = createField("MarketingSegmentationCluster", "Marketing Segmentation Cluster", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField75);
        final SObjectField sObjectField76 = createField("ImportExportAgent", "Import/Export", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField76);
        final SObjectField sObjectField77 = createField("Subsidiary", "Subsidiary Indicator", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField77);
        final SObjectField sObjectField78 = createField("TradeStyle2", "Second Tradestyle", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField78);
        final SObjectField sObjectField79 = createField("TradeStyle3", "Third Tradestyle", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField79);
        final SObjectField sObjectField80 = createField("TradeStyle4", "Fourth Tradestyle", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField80);
        final SObjectField sObjectField81 = createField("TradeStyle5", "Fifth Tradestyle", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField81);
        final SObjectField sObjectField82 = createField("NationalId", "National Identification Number", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField82);
        final SObjectField sObjectField83 = createField("NationalIdType", "National Identification System", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField83);
        final SObjectField sObjectField84 = createField("UsTaxId", "US Tax ID Number", "string", "xsd:string", 9, false, true, false, false, false, false, false);
        fields1.add(sObjectField84);
        final SObjectField sObjectField85 = createField("GeoCodeAccuracy", "Geocode Accuracy", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField85);
        final SObjectField sObjectField86 = createField("FamilyMembers", "Number of Business Family Members", "int", "xsd:int", 0, false, true, false, false, false, false, false);
        fields1.add(sObjectField86);
        final SObjectField sObjectField87 = createField("MarketingPreScreen", "Delinquency Risk", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField87);
        final SObjectField sObjectField88 = createField("GlobalUltimateDunsNumber", "Global Ultimate D-U-N-S Number", "string", "xsd:string", 9, false, true, false, false, false, false, false);
        fields1.add(sObjectField88);
        final SObjectField sObjectField89 = createField("GlobalUltimateBusinessName", "Global Ultimate Business Name", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField89);
        final SObjectField sObjectField90 = createField("ParentOrHqDunsNumber", "Parent Company D-U-N-S Number", "string", "xsd:string", 9, false, true, false, false, false, false, false);
        fields1.add(sObjectField90);
        final SObjectField sObjectField91 = createField("ParentOrHqBusinessName", "Parent Company Business Name", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField91);
        final SObjectField sObjectField92 = createField("DomesticUltimateDunsNumber", "Domestic Ultimate D-U-N-S Number", "string", "xsd:string", 9, false, true, false, false, false, false, false);
        fields1.add(sObjectField92);
        final SObjectField sObjectField93 = createField("DomesticUltimateBusinessName", "Domestic Ultimate Business Name", "string", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField93);
        final SObjectField sObjectField94 = createField("LocationStatus", "Location Type", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField94);
        final SObjectField sObjectField95 = createField("CompanyCurrencyIsoCode", "Local Currency ISO Code", "picklist", "xsd:string", 255, false, true, false, false, false, false, false);
        fields1.add(sObjectField95);
        final SObjectField sObjectField96 = createField("Description", "Company Description", "textarea", "xsd:string", 32000, false, true, false, false, false, false, false);
        fields1.add(sObjectField96);

        description.setLabel("D&B Company");
        description.setLabelPlural("D&B Companies");
        description.setName("DandBCompany");

        final SObjectDescriptionUrls sObjectDescriptionUrls1 = new SObjectDescriptionUrls();
        sObjectDescriptionUrls1.setCompactLayouts("/services/data/v34.0/sobjects/DandBCompany/describe/compactLayouts");
        sObjectDescriptionUrls1.setDescribe("/services/data/v34.0/sobjects/DandBCompany/describe");
        sObjectDescriptionUrls1.setLayouts("/services/data/v34.0/sobjects/DandBCompany/describe/layouts");
        sObjectDescriptionUrls1.setRowTemplate("/services/data/v34.0/sobjects/DandBCompany/{ID}");
        sObjectDescriptionUrls1.setSobject("/services/data/v34.0/sobjects/DandBCompany");
        sObjectDescriptionUrls1.setUiDetailTemplate("https://gabrielchanca-dev-ed.my.salesforce.com/{ID}");
        sObjectDescriptionUrls1.setUiEditTemplate("https://gabrielchanca-dev-ed.my.salesforce.com/{ID}/e");
        sObjectDescriptionUrls1.setUiNewRecord("https://gabrielchanca-dev-ed.my.salesforce.com/06E/e");
        description.setUrls(sObjectDescriptionUrls1);

        return description;
    }
}
