/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist WomenOwned
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum DandBCompany_WomenOwnedEnum {

    // N
    N("N"),

    // Y
    Y("Y");


    final String value;

    private DandBCompany_WomenOwnedEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_WomenOwnedEnum fromValue(String value) {
        for (DandBCompany_WomenOwnedEnum e : DandBCompany_WomenOwnedEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
