/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist OutOfBusiness
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum DandBCompany_OutOfBusinessEnum {

    // N
    N("N"),

    // Y
    Y("Y");


    final String value;

    private DandBCompany_OutOfBusinessEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_OutOfBusinessEnum fromValue(String value) {
        for (DandBCompany_OutOfBusinessEnum e : DandBCompany_OutOfBusinessEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
