/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum EmailMessage_StatusEnum {

    // 0
    _0("0"),

    // 1
    _1("1"),

    // 2
    _2("2"),

    // 3
    _3("3"),

    // 4
    _4("4"),

    // 5
    _5("5");


    final String value;

    private EmailMessage_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static EmailMessage_StatusEnum fromValue(String value) {
        for (EmailMessage_StatusEnum e : EmailMessage_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
