/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RecurrenceType
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Event_RecurrenceTypeEnum {

    // RecursDaily
    RECURSDAILY("RecursDaily"),

    // RecursEveryWeekday
    RECURSEVERYWEEKDAY("RecursEveryWeekday"),

    // RecursMonthly
    RECURSMONTHLY("RecursMonthly"),

    // RecursMonthlyNth
    RECURSMONTHLYNTH("RecursMonthlyNth"),

    // RecursWeekly
    RECURSWEEKLY("RecursWeekly"),

    // RecursYearly
    RECURSYEARLY("RecursYearly"),

    // RecursYearlyNth
    RECURSYEARLYNTH("RecursYearlyNth");


    final String value;

    private Event_RecurrenceTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Event_RecurrenceTypeEnum fromValue(String value) {
        for (Event_RecurrenceTypeEnum e : Event_RecurrenceTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
