/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RecurrenceMonthOfYear
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Event_RecurrenceMonthOfYearEnum {

    // April
    APRIL("April"),

    // August
    AUGUST("August"),

    // December
    DECEMBER("December"),

    // February
    FEBRUARY("February"),

    // January
    JANUARY("January"),

    // July
    JULY("July"),

    // June
    JUNE("June"),

    // March
    MARCH("March"),

    // May
    MAY("May"),

    // November
    NOVEMBER("November"),

    // October
    OCTOBER("October"),

    // September
    SEPTEMBER("September");


    final String value;

    private Event_RecurrenceMonthOfYearEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Event_RecurrenceMonthOfYearEnum fromValue(String value) {
        for (Event_RecurrenceMonthOfYearEnum e : Event_RecurrenceMonthOfYearEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
