/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PrincipalType
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum NamedCredential_PrincipalTypeEnum {

    // Anonymous
    ANONYMOUS("Anonymous"),

    // NamedUser
    NAMEDUSER("NamedUser"),

    // PerUser
    PERUSER("PerUser");


    final String value;

    private NamedCredential_PrincipalTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static NamedCredential_PrincipalTypeEnum fromValue(String value) {
        for (NamedCredential_PrincipalTypeEnum e : NamedCredential_PrincipalTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
