/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type PricebookEntry
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsPricebookEntry extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<PricebookEntry> records;

    public List<PricebookEntry> getRecords() {
        return records;
    }

    public void setRecords(List<PricebookEntry> records) {
        this.records = records;
    }
}
