/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;
import javax.annotation.Generated;

/**
 * Salesforce QueryRecords DTO for type Event
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public class QueryRecordsEvent extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<Event> records;

    public List<Event> getRecords() {
        return records;
    }

    public void setRecords(List<Event> records) {
        this.records = records;
    }
}
