/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Channel
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum QuickText_ChannelEnum {

    // Email
    EMAIL("Email"),

    // Event
    EVENT("Event"),

    // Internal
    INTERNAL("Internal"),

    // Phone
    PHONE("Phone"),

    // Portal
    PORTAL("Portal"),

    // Task
    TASK("Task");


    final String value;

    private QuickText_ChannelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static QuickText_ChannelEnum fromValue(String value) {
        for (QuickText_ChannelEnum e : QuickText_ChannelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
