/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Category
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum QuickText_CategoryEnum {

    // Closings
    CLOSINGS("Closings"),

    // FAQ
    FAQ("FAQ"),

    // Greetings
    GREETINGS("Greetings");


    final String value;

    private QuickText_CategoryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static QuickText_CategoryEnum fromValue(String value) {
        for (QuickText_CategoryEnum e : QuickText_CategoryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
