/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Priority
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Task_PriorityEnum {

    // High
    HIGH("High"),

    // Low
    LOW("Low"),

    // Normal
    NORMAL("Normal");


    final String value;

    private Task_PriorityEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Task_PriorityEnum fromValue(String value) {
        for (Task_PriorityEnum e : Task_PriorityEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
