/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Task_StatusEnum {

    // Completed
    COMPLETED("Completed"),

    // Deferred
    DEFERRED("Deferred"),

    // In Progress
    IN_PROGRESS("In Progress"),

    // Not Started
    NOT_STARTED("Not Started"),

    // Waiting on someone else
    WAITING_ON_SOMEONE_ELSE("Waiting on someone else");


    final String value;

    private Task_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Task_StatusEnum fromValue(String value) {
        for (Task_StatusEnum e : Task_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
