/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Operation
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum UserProvisioningRequest_OperationEnum {

    // Activate
    ACTIVATE("Activate"),

    // Create
    CREATE("Create"),

    // Deactivate
    DEACTIVATE("Deactivate"),

    // Freeze
    FREEZE("Freeze"),

    // Linking
    LINKING("Linking"),

    // Read
    READ("Read"),

    // Reconcile
    RECONCILE("Reconcile"),

    // Unfreeze
    UNFREEZE("Unfreeze"),

    // Update
    UPDATE("Update");


    final String value;

    private UserProvisioningRequest_OperationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserProvisioningRequest_OperationEnum fromValue(String value) {
        for (UserProvisioningRequest_OperationEnum e : UserProvisioningRequest_OperationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
